inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Exclude:
    - 'spec/**/*'
