name: CI

on:
  pull_request:

  push:
    branches: [master]

env:
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.ref }}

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop --format progress
  build:
    needs: [linting]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5.x', '2.6.x', '2.7.x']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
